// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	gax "github.com/googleapis/gax-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// MockGCPOperation is an autogenerated mock type for the GCPOperation type
type MockGCPOperation struct {
	mock.Mock
}

// Wait provides a mock function with given fields: ctx, opts
func (_m *MockGCPOperation) Wait(ctx context.Context, opts ...gax.CallOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Wait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...gax.CallOption) error); ok {
		r0 = rf(ctx, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockGCPOperation creates a new instance of MockGCPOperation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCPOperation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCPOperation {
	mock := &MockGCPOperation{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
