// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	computepb "cloud.google.com/go/compute/apiv1/computepb"

	mock "github.com/stretchr/testify/mock"
)

// MockGCPInstances is an autogenerated mock type for the GCPInstances type
type MockGCPInstances struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockGCPInstances) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstances) Delete(_a0 context.Context, _a1 *computepb.DeleteInstanceRequest) (GCPOperation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 GCPOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.DeleteInstanceRequest) (GCPOperation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.DeleteInstanceRequest) GCPOperation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(GCPOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.DeleteInstanceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstances) Get(_a0 context.Context, _a1 *computepb.GetInstanceRequest) (*computepb.Instance, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *computepb.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.GetInstanceRequest) (*computepb.Instance, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.GetInstanceRequest) *computepb.Instance); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*computepb.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.GetInstanceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListAll provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstances) ListAll(_a0 context.Context, _a1 *computepb.ListInstancesRequest) ([]*computepb.Instance, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListAll")
	}

	var r0 []*computepb.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.ListInstancesRequest) ([]*computepb.Instance, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.ListInstancesRequest) []*computepb.Instance); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*computepb.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.ListInstancesRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGCPInstances creates a new instance of MockGCPInstances. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCPInstances(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCPInstances {
	mock := &MockGCPInstances{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
