// Code generated by mockery v2.53.5. DO NOT EDIT.

package ifaces

import (
	context "context"

	computepb "cloud.google.com/go/compute/apiv1/computepb"

	mock "github.com/stretchr/testify/mock"
)

// MockGCPInstanceGroupManagers is an autogenerated mock type for the GCPInstanceGroupManagers type
type MockGCPInstanceGroupManagers struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *MockGCPInstanceGroupManagers) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInstances provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstanceGroupManagers) DeleteInstances(_a0 context.Context, _a1 *computepb.DeleteInstancesInstanceGroupManagerRequest) (GCPOperation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInstances")
	}

	var r0 GCPOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.DeleteInstancesInstanceGroupManagerRequest) (GCPOperation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.DeleteInstancesInstanceGroupManagerRequest) GCPOperation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(GCPOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.DeleteInstancesInstanceGroupManagerRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstanceGroupManagers) Get(_a0 context.Context, _a1 *computepb.GetInstanceGroupManagerRequest) (*computepb.InstanceGroupManager, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *computepb.InstanceGroupManager
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.GetInstanceGroupManagerRequest) (*computepb.InstanceGroupManager, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.GetInstanceGroupManagerRequest) *computepb.InstanceGroupManager); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*computepb.InstanceGroupManager)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.GetInstanceGroupManagerRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListManagedInstancesAll provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstanceGroupManagers) ListManagedInstancesAll(_a0 context.Context, _a1 *computepb.ListManagedInstancesInstanceGroupManagersRequest) ([]*computepb.ManagedInstance, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ListManagedInstancesAll")
	}

	var r0 []*computepb.ManagedInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.ListManagedInstancesInstanceGroupManagersRequest) ([]*computepb.ManagedInstance, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.ListManagedInstancesInstanceGroupManagersRequest) []*computepb.ManagedInstance); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*computepb.ManagedInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.ListManagedInstancesInstanceGroupManagersRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resize provides a mock function with given fields: _a0, _a1
func (_m *MockGCPInstanceGroupManagers) Resize(_a0 context.Context, _a1 *computepb.ResizeInstanceGroupManagerRequest) (GCPOperation, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Resize")
	}

	var r0 GCPOperation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.ResizeInstanceGroupManagerRequest) (GCPOperation, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *computepb.ResizeInstanceGroupManagerRequest) GCPOperation); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(GCPOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *computepb.ResizeInstanceGroupManagerRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockGCPInstanceGroupManagers creates a new instance of MockGCPInstanceGroupManagers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGCPInstanceGroupManagers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGCPInstanceGroupManagers {
	mock := &MockGCPInstanceGroupManagers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
